name: 'cce-build-and-deploy-docker-image'
author: 'CleanChoice Energy'
description: 'Composite action comprised of creating an .npmrc file, logging into ECR, and creating and deploying an image to AWS ECR'
inputs:
  environment-prefix:
    description: 'dev, staging, prod, etc'
    required: true
outputs:
  aws-account-id:
    description: 'The AWS account ID for the provided credentials'
runs:
  using: 'composite'
  steps:
    - name: Install aws-iam-authenticator
      run: curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/aws-iam-authenticator && chmod +x ./aws-iam-authenticator
    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Create .npmrc file
      run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > .npmrc
    - name: Build and tag image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > .npmrc
        docker build -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ github.sha }} . --build-arg ENV_PREFIX=${{ inputs.environment-prefix }}
        docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
    - name: Push image to ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ github.sha }}