name: 'cce-build-and-deploy-docker-image'
author: 'CleanChoice Energy'
description: 'Composite action comprised of creating an .npmrc file, logging into ECR, and creating and deploying an image to AWS ECR'
inputs:
  environment-prefix:
    description: 'dev, staging, prod, etc'
    required: true
  repository:
    description: 'Name of ECR repository, should match Github repository'
    required: true
  npm-auth-token:
    description: 'NPM Auth token needed for NodeJS applications'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Install aws-iam-authenticator
      shell: bash
      run: curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/aws-iam-authenticator && chmod +x ./aws-iam-authenticator
    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Create .npmrc file
      shell: bash
      run: |
          echo "//registry.npmjs.org/:_authToken=${{ inputs.npm-auth-token }}" > .npmrc
    - name: Build and push docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.repository }}:${{ github.sha }}
        build-args: ${{ inputs.environment-prefix }}